/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RectoTecnico;

import javax.swing.JOptionPane;

/**
 *
 * @author CAMILO
 */
public class TiposNave extends javax.swing.JFrame {

    /**
     * Creates new form TiposNave
     */
    public TiposNave() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TiposNave = new javax.swing.ButtonGroup();
        rdbLanzadera = new javax.swing.JRadioButton();
        rdbNoTripulada = new javax.swing.JRadioButton();
        rdbTripulada = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        BtnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TiposNave.add(rdbLanzadera);
        rdbLanzadera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbLanzadera.setText("VEHÍCULOS LANZADERA");
        rdbLanzadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLanzaderaActionPerformed(evt);
            }
        });

        TiposNave.add(rdbNoTripulada);
        rdbNoTripulada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbNoTripulada.setText("NAVES ESPACIALES NO TRIPULADAS");

        TiposNave.add(rdbTripulada);
        rdbTripulada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbTripulada.setText("NAVES ESPACIALES TRIPULADAS");

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        BtnConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnConsultar.setText("CONSULTAR");
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbNoTripulada)
                    .addComponent(rdbLanzadera)
                    .addComponent(rdbTripulada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rdbLanzadera)
                .addGap(18, 18, 18)
                .addComponent(rdbNoTripulada)
                .addGap(18, 18, 18)
                .addComponent(rdbTripulada)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbLanzaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLanzaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbLanzaderaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        if(rdbLanzadera.isSelected()==true){

            OpcLanzadora verOpcLanzadora = new OpcLanzadora();
            verOpcLanzadora.setVisible(true);
            this.dispose();
        }else if(rdbNoTripulada.isSelected()==true){

            OpcNoTripuladas verOpcNoTripuladas = new OpcNoTripuladas();
            verOpcNoTripuladas.setVisible(true);
            this.dispose();
        }else if(rdbTripulada.isSelected()==true){

            OpcTripuladas verOpcTripuladas = new OpcTripuladas();
            verOpcTripuladas.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Celecione un campo");
        }
        
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio verInicio = new Inicio();
        verInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Inicio verInicio = new Inicio();
        verInicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed

        if(rdbLanzadera.isSelected()==true){

            ConsulLanzadora verOpcLanzadora = new ConsulLanzadora();
            verOpcLanzadora.setVisible(true);
            this.dispose();
        }else if(rdbNoTripulada.isSelected()==true){

            ConsulNoTripulada verOpcNoTripuladas = new ConsulNoTripulada();
            verOpcNoTripuladas.setVisible(true);
            this.dispose();
        }else if(rdbTripulada.isSelected()==true){

            ConsulTripuladas verOpcTripuladas = new ConsulTripuladas();
            verOpcTripuladas.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Celecione un campo");
        }
        
    }//GEN-LAST:event_BtnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiposNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiposNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiposNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiposNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiposNave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.ButtonGroup TiposNave;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JRadioButton rdbLanzadera;
    private javax.swing.JRadioButton rdbNoTripulada;
    private javax.swing.JRadioButton rdbTripulada;
    // End of variables declaration//GEN-END:variables
}
